import { CityConfig } from '../types';

export const BENGALURU_CONFIG: CityConfig = {
  id: 'bengaluru',
  name: 'Bengaluru',
  state: 'Karnataka',
  country: 'India',
  currencySymbol: '₹',
  currencyCode: 'INR',
  supportHelpline: '1800-102-साथी',
  supportTel: 'tel:18001027288',
  supportWhatsAppNumber: '+91 80 4821 9900',
  operationsDeskName: 'Bengaluru East Operations Hub',
  defaultClusterId: 'indiranagar',
  searchRadiusKm: 2.5,
  localUtilityProvider: {
    name: 'BESCOM',
    type: 'Electricity Supply Company',
    helpline: '1912',
    sosLabel: 'BESCOM SOS',
  },
  tradeCompliance: {
    authority: 'Karnataka PWD & Electrical Inspectorate',
    wiremanLicenseName: 'BESCOM Grade-A Wireman License',
    itiDiplomaAuthority: 'Dept of Employment & Training, Karnataka',
    insuranceUnderwriter: 'ICICI-LOMB-77291',
    trafficGridName: 'Bengaluru East Traffic Grid',
    gstin: '29AAGCS0091R1Z9',
  },
  demoUser: {
    name: 'Priya M.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0jvPP9BqfTgRvSFtPoRv1XBASZQr--39R7ro2SLoEOHAu7q-l8VS6oYJGtO2oMgwc5WsZGvP6UrzWuooM3jFJ2z33ozxBMSZOupgdYge6Tc5XpCKZPoEFhlH0QGVTPh1jWETGNq4kVt8z5_cOChFZA-yTJ501t-hyRVbYoGLDq4oKID9xoY5gdsVK4_ce39h6vyCXRw4ms2BbY2gI_FkswL8kI1X7QZm02q1GzVvXgdhXmSks08ZI',
    defaultAddress: '42, 12th Main Rd, Indiranagar',
    landmark: 'Opposite Kaveri Sweets, blue gate, take elevator to 3rd floor (Flat 302)',
    phone: '+91 98450 12891',
  },
  pricing: {
    baseInspectionFee: 99,
    inspectionWaiveThreshold: 300,
    platformSafetyFee: 15,
    firstTimeDiscount: 15,
    lateCancellationFee: 50,
    freeCancellationMinutes: 2,
    warrantyDays: 30,
    providerFlatFee: 20,
    gstPercent: 18,
  },
  clusters: [
    {
      id: 'indiranagar',
      name: 'Indiranagar Hub',
      area: '100ft Rd, Defense Colony & HAL 2nd Stage',
      activeProsCount: 14,
      avgArrivalMins: 14,
      surgeActive: true,
      surgeMultiplier: 1.2,
      surgeReason: 'High emergency demand & evening commute load',
      trafficCondition: 'moderate',
      trafficCorridor: '100ft Rd & 12th Main corridor',
      coordinates: { lat: 12.9784, lng: 77.6408 },
    },
    {
      id: 'koramangala',
      name: 'Koramangala 4th Block',
      area: 'Sony Signal, 80ft Rd & 5th Block',
      activeProsCount: 11,
      avgArrivalMins: 18,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: '80ft Rd & Sony Signal corridor',
      coordinates: { lat: 12.9352, lng: 77.6245 },
    },
    {
      id: 'domlur',
      name: 'Domlur & EGL Zone',
      area: 'Embassy Golf Links & Inner Ring Rd',
      activeProsCount: 8,
      avgArrivalMins: 16,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: 'Inner Ring Rd corridor',
      coordinates: { lat: 12.9609, lng: 77.6387 },
    },
    {
      id: 'hsr',
      name: 'HSR Layout Sector 1',
      area: '27th Main & 19th Main Hub',
      activeProsCount: 12,
      avgArrivalMins: 20,
      surgeActive: true,
      surgeMultiplier: 1.15,
      surgeReason: 'Pre-monsoon power line check surge',
      trafficCondition: 'dense',
      trafficCorridor: '27th Main & Silk Board approach',
      coordinates: { lat: 12.9121, lng: 77.6446 },
    },
  ],
};

// Ready-to-use alternative city configurations to verify modularity
export const MUMBAI_CONFIG: CityConfig = {
  id: 'mumbai',
  name: 'Mumbai',
  state: 'Maharashtra',
  country: 'India',
  currencySymbol: '₹',
  currencyCode: 'INR',
  supportHelpline: '1800-102-साथी',
  supportTel: 'tel:18001027288',
  supportWhatsAppNumber: '+91 22 4821 9900',
  operationsDeskName: 'Mumbai Western Suburbs Operations Hub',
  defaultClusterId: 'bandra-west',
  searchRadiusKm: 2.5,
  localUtilityProvider: {
    name: 'Adani Electricity / BEST',
    type: 'Electricity Distribution',
    helpline: '19122',
    sosLabel: 'Adani Power SOS',
  },
  tradeCompliance: {
    authority: 'Maharashtra PWD Electrical Inspectorate',
    wiremanLicenseName: 'Maharashtra State Grade-A Wireman License',
    itiDiplomaAuthority: 'Directorate of Vocational Education, Maharashtra',
    insuranceUnderwriter: 'TATA-AIG-99124',
    trafficGridName: 'Mumbai Suburbs Traffic Grid',
    gstin: '27AAGCS0091R1Z1',
  },
  demoUser: {
    name: 'Rohit S.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0jvPP9BqfTgRvSFtPoRv1XBASZQr--39R7ro2SLoEOHAu7q-l8VS6oYJGtO2oMgwc5WsZGvP6UrzWuooM3jFJ2z33ozxBMSZOupgdYge6Tc5XpCKZPoEFhlH0QGVTPh1jWETGNq4kVt8z5_cOChFZA-yTJ501t-hyRVbYoGLDq4oKID9xoY5gdsVK4_ce39h6vyCXRw4ms2BbY2gI_FkswL8kI1X7QZm02q1GzVvXgdhXmSks08ZI',
    defaultAddress: '14, Perry Cross Rd, Bandra West',
    landmark: 'Behind St. Andrews Church, Green Villa (Flat 101)',
    phone: '+91 98200 44211',
  },
  pricing: {
    baseInspectionFee: 99,
    inspectionWaiveThreshold: 300,
    platformSafetyFee: 15,
    firstTimeDiscount: 15,
    lateCancellationFee: 50,
    freeCancellationMinutes: 2,
    warrantyDays: 30,
    providerFlatFee: 20,
    gstPercent: 18,
  },
  clusters: [
    {
      id: 'bandra-west',
      name: 'Bandra West Hub',
      area: 'Hill Rd, Pali Hill & Carter Rd',
      activeProsCount: 16,
      avgArrivalMins: 15,
      surgeActive: true,
      surgeMultiplier: 1.25,
      surgeReason: 'High weekend resident callout volume',
      trafficCondition: 'moderate',
      trafficCorridor: 'Hill Rd & Linking Rd corridor',
      coordinates: { lat: 19.0596, lng: 72.8295 },
    },
    {
      id: 'andheri-west',
      name: 'Andheri West Hub',
      area: 'Lokhandwala, Oshiwara & Link Rd',
      activeProsCount: 18,
      avgArrivalMins: 16,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: 'Link Rd & Infinity Mall corridor',
      coordinates: { lat: 19.1363, lng: 72.8277 },
    },
    {
      id: 'powai',
      name: 'Powai Lake Hub',
      area: 'Hiranandani Gardens & JVLR',
      activeProsCount: 10,
      avgArrivalMins: 19,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: 'Central Ave & JVLR corridor',
      coordinates: { lat: 19.1176, lng: 72.906 },
    },
  ],
};

export const DELHI_NCR_CONFIG: CityConfig = {
  id: 'delhi',
  name: 'Delhi NCR',
  state: 'Delhi',
  country: 'India',
  currencySymbol: '₹',
  currencyCode: 'INR',
  supportHelpline: '1800-102-साथी',
  supportTel: 'tel:18001027288',
  supportWhatsAppNumber: '+91 11 4821 9900',
  operationsDeskName: 'Delhi South Operations Hub',
  defaultClusterId: 'south-delhi',
  searchRadiusKm: 3.0,
  localUtilityProvider: {
    name: 'BSES Rajdhani',
    type: 'Power Distribution',
    helpline: '19123',
    sosLabel: 'BSES Emergency SOS',
  },
  tradeCompliance: {
    authority: 'Delhi Electrical Inspectorate, GNCTD',
    wiremanLicenseName: 'Delhi State Grade-A Wireman License',
    itiDiplomaAuthority: 'DTTE, Delhi Administration',
    insuranceUnderwriter: 'HDFC-ERGO-88192',
    trafficGridName: 'Delhi South Traffic Grid',
    gstin: '07AAGCS0091R1Z5',
  },
  demoUser: {
    name: 'Sameer V.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0jvPP9BqfTgRvSFtPoRv1XBASZQr--39R7ro2SLoEOHAu7q-l8VS6oYJGtO2oMgwc5WsZGvP6UrzWuooM3jFJ2z33ozxBMSZOupgdYge6Tc5XpCKZPoEFhlH0QGVTPh1jWETGNq4kVt8z5_cOChFZA-yTJ501t-hyRVbYoGLDq4oKID9xoY5gdsVK4_ce39h6vyCXRw4ms2BbY2gI_FkswL8kI1X7QZm02q1GzVvXgdhXmSks08ZI',
    defaultAddress: 'E-24, Hauz Khas Enclave',
    landmark: 'Near Aurobindo Market, 2nd floor',
    phone: '+91 98110 55421',
  },
  pricing: {
    baseInspectionFee: 99,
    inspectionWaiveThreshold: 300,
    platformSafetyFee: 15,
    firstTimeDiscount: 15,
    lateCancellationFee: 50,
    freeCancellationMinutes: 2,
    warrantyDays: 30,
    providerFlatFee: 20,
    gstPercent: 18,
  },
  clusters: [
    {
      id: 'south-delhi',
      name: 'South Delhi Hub',
      area: 'Hauz Khas, Greater Kailash & Saket',
      activeProsCount: 20,
      avgArrivalMins: 14,
      surgeActive: true,
      surgeMultiplier: 1.2,
      surgeReason: 'High demand in residential zones',
      trafficCondition: 'moderate',
      trafficCorridor: 'Outer Ring Rd & August Kranti Marg',
      coordinates: { lat: 28.5494, lng: 77.2001 },
    },
    {
      id: 'gurugram-cybercity',
      name: 'Gurugram Cyber Hub',
      area: 'DLF Phase 2, Golf Course Rd & Sector 43',
      activeProsCount: 15,
      avgArrivalMins: 16,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: 'Golf Course Rd corridor',
      coordinates: { lat: 28.4897, lng: 77.0898 },
    },
    {
      id: 'noida-sector62',
      name: 'Noida Central Hub',
      area: 'Sector 18, Sector 62 & Expressway',
      activeProsCount: 14,
      avgArrivalMins: 18,
      surgeActive: false,
      surgeMultiplier: 1.0,
      trafficCondition: 'clear',
      trafficCorridor: 'Noida Expressway corridor',
      coordinates: { lat: 28.628, lng: 77.3649 },
    },
  ],
};

export const AVAILABLE_CITIES: Record<string, CityConfig> = {
  bengaluru: BENGALURU_CONFIG,
  mumbai: MUMBAI_CONFIG,
  delhi: DELHI_NCR_CONFIG,
};

export const DEFAULT_ACTIVE_CITY = BENGALURU_CONFIG;

// Pricing Calculation Helper based on active city rules
export function calculateJobInvoiceTotal(
  laborFee: number,
  partsTotal: number,
  pricing: CityConfig['pricing'],
  customTip: number = 0
) {
  const isVisitFeeWaived = (laborFee + partsTotal) >= pricing.inspectionWaiveThreshold;
  const effectiveVisitFee = isVisitFeeWaived ? 0 : pricing.baseInspectionFee;
  const platformSafetyFee = pricing.platformSafetyFee;
  const discount = pricing.firstTimeDiscount;
  const gstTax = Math.round((platformSafetyFee * pricing.gstPercent) / 100);
  const grandTotal = effectiveVisitFee + laborFee + partsTotal + platformSafetyFee - discount + gstTax + customTip;

  return {
    effectiveVisitFee,
    isVisitFeeWaived,
    platformSafetyFee,
    discount,
    gstTax,
    grandTotal: Math.max(grandTotal, 0),
    warrantyDays: pricing.warrantyDays,
  };
}

export function formatCurrency(amount: number, symbol: string = '₹'): string {
  return `${symbol}${amount.toLocaleString('en-IN')}`;
}
